{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyMeJ4bnZq2ietMzDfpFOVD2"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","execution_count":1,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"aohPMd5uEkF8","executionInfo":{"status":"ok","timestamp":1697771636926,"user_tz":-480,"elapsed":6549,"user":{"displayName":"REDACTED REDACTED REDACTED","userId":"15429921224172384235"}},"outputId":"8f4f5655-6d27-401c-e737-cc89821448e4"},"outputs":[{"output_type":"stream","name":"stdout","text":["Collecting perplexityai\n","  Downloading perplexityai-1.0.1-py3-none-any.whl (10 kB)\n","Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from perplexityai) (2.31.0)\n","Requirement already satisfied: websocket-client in /usr/local/lib/python3.10/dist-packages (from perplexityai) (1.6.4)\n","Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->perplexityai) (3.3.0)\n","Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->perplexityai) (3.4)\n","Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->perplexityai) (2.0.7)\n","Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->perplexityai) (2023.7.22)\n","Installing collected packages: perplexityai\n","Successfully installed perplexityai-1.0.1\n"]}],"source":["!pip install -U perplexityai"]},{"cell_type":"code","source":["import perplexityai\n","from asyncio import run\n","\n","\n","async def main():\n","    while True:\n","        prompt = input(\"ðŸ‘¦: \")\n","        try:\n","            resp = await perplexityai.Completion.create(prompt)\n","            print(f\"ðŸ¤–: {resp}\")\n","        except Exception as e:\n","            print(f\"ðŸ¤–: {e}\")\n","\n","\n","run(main())"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":332},"id":"cycyJVvIEw48","executionInfo":{"status":"error","timestamp":1697771646761,"user_tz":-480,"elapsed":21,"user":{"displayName":"REDACTED REDACTED REDACTED","userId":"15429921224172384235"}},"outputId":"f5ae12af-27a8-474b-92dd-ff1aa8bf34f2"},"execution_count":2,"outputs":[{"output_type":"error","ename":"RuntimeError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)","\u001b[0;32m<ipython-input-2-a89a53f35315>\u001b[0m in \u001b[0;36m<cell line: 15>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     13\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     14\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 15\u001b[0;31m \u001b[0mrun\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmain\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m/usr/lib/python3.10/asyncio/runners.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(main, debug)\u001b[0m\n\u001b[1;32m     31\u001b[0m     \"\"\"\n\u001b[1;32m     32\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mevents\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_get_running_loop\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 33\u001b[0;31m         raise RuntimeError(\n\u001b[0m\u001b[1;32m     34\u001b[0m             \"asyncio.run() cannot be called from a running event loop\")\n\u001b[1;32m     35\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mRuntimeError\u001b[0m: asyncio.run() cannot be called from a running event loop"]}]},{"cell_type":"code","source":[],"metadata":{"id":"ZJHAlmN8E2q9"},"execution_count":null,"outputs":[]}]}